import type { Product } from '../types/product';

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Brake Pads Set',
        description: 'Ceramic brake pads for front wheels - Premium quality',
        sku: 'BP-F-001',
        price: 89.99,
        cost: 45.00,
        category: 'Brakes',
        supplier: 'AutoParts Direct',
        stock: 45,
        minStock: 15,
        maxStock: 100,
        imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Oil Filter',
        description: 'High-performance oil filter - Compatible with most engines',
        sku: 'OF-STD-002',
        price: 12.99,
        cost: 6.50,
        category: 'Filters',
        supplier: 'FilterPro Inc',
        stock: 250,
        minStock: 50,
        maxStock: 300,
        imageUrl: 'https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        name: 'Spark Plugs (Set of 4)',
        description: 'Iridium spark plugs for improved performance',
        sku: 'SP-IR-003',
        price: 34.99,
        cost: 18.00,
        category: 'Ignition',
        supplier: 'Ignition Masters',
        stock: 120,
        minStock: 30,
        maxStock: 200,
        imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '4',
        name: 'Air Filter',
        description: 'High-flow air filter for better engine breathing',
        sku: 'AF-HF-004',
        price: 24.99,
        cost: 12.00,
        category: 'Filters',
        supplier: 'FilterPro Inc',
        stock: 8,
        minStock: 20,
        maxStock: 150,
        imageUrl: 'https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '5',
        name: 'Alternator',
        description: '120A alternator - Remanufactured with warranty',
        sku: 'ALT-120-005',
        price: 189.99,
        cost: 95.00,
        category: 'Electrical',
        supplier: 'Electric Auto Parts',
        stock: 15,
        minStock: 5,
        maxStock: 30,
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '6',
        name: 'Radiator',
        description: 'Aluminum radiator with enhanced cooling capacity',
        sku: 'RAD-AL-006',
        price: 249.99,
        cost: 125.00,
        category: 'Cooling',
        supplier: 'CoolTech Parts',
        stock: 12,
        minStock: 5,
        maxStock: 25,
        imageUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '7',
        name: 'Shock Absorbers (Pair)',
        description: 'Heavy-duty shock absorbers for rear suspension',
        sku: 'SA-HD-007',
        price: 159.99,
        cost: 80.00,
        category: 'Suspension',
        supplier: 'Suspension Pro',
        stock: 28,
        minStock: 10,
        maxStock: 50,
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '8',
        name: 'Timing Belt Kit',
        description: 'Complete timing belt kit with tensioner and pulleys',
        sku: 'TB-KIT-008',
        price: 129.99,
        cost: 65.00,
        category: 'Engine',
        supplier: 'Engine Parts Co',
        stock: 35,
        minStock: 15,
        maxStock: 60,
        imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];
